const userModule = require("../models/User")
const {StatusCodes} = require("http-status-codes")
const bcrypt = require("bcryptjs")
const jwt = require("jsonwebtoken")


const Register = async (req, res) => {
    const { name, email, password } = req.body

    const salt = await bcrypt.genSalt(10) //to generate random bytes
    const hashedPassword = await bcrypt.hash(password, salt) //hash the password with the generated bytes

    const tempUser = {name, email, password: hashedPassword}
    const user = await userModule.create({...tempUser})

 res.status(StatusCodes.CREATED).json({success: true, data: user})
}

const Login = async (req, res) => {
 res.send("welcome back chief")
}


module.exports = {
    Register,
    Login
}